import { MiddlewareConsumer, Module, type NestModule } from '@nestjs/common'
import { ConfigModule } from '@nestjs/config'
import { VisitorMiddleware } from './api/visitor.middleware'
import { DiscoverController } from './api/discover.controller'
import { FavoritesController } from './api/favorites.controller'
import { HistoryController } from './api/history.controller'
import { HotelsController } from './api/hotels.controller'
import { InspirationController } from './api/inspiration.controller'
import { McpController } from './api/mcp.controller'
import { TasksController } from './api/tasks.controller'
import { TranslationController } from './api/translation.controller'
import { TravelController } from './api/travel.controller'
import { VisitorsController } from './api/visitors.controller'
import { CoordinatorService } from './agents/coordinator'
import { CriticAgent } from './agents/critic'
import { IntentAgent } from './agents/intent'
import { PlannerAgent } from './agents/planner'
import { ResearchAgent } from './agents/research'
import { BilibiliProvider } from './agents/tools/bilibili'
import { DouyinProvider } from './agents/tools/douyin'
import { LlmService } from './agents/tools/llm-client'
import { McpClientService } from './agents/tools/mcp-client'
import { McpRegistryService } from './agents/tools/mcp-registry'
import { OpenAiCompatibleProvider } from './agents/tools/openai-compatible'
import { WeiboProvider } from './agents/tools/weibo'
import { KstayProvider } from './agents/tools/kstay'
import { XiaohongshuProvider } from './agents/tools/xiaohongshu'
import { TavilyInspirationProvider } from './agents/tools/tavily-inspiration'
import { PrismaService } from './db/prisma.service'
import { DiscoverService } from './services/discover.service'
import { FavoritesService } from './services/favorites.service'
import { HotelsService } from './services/hotels.service'
import { InspirationService } from './services/inspiration.service'
import { QueueService } from './services/queue.service'
import { TasksService } from './services/tasks.service'
import { TranslationService } from './services/translation.service'

const controllers = [TasksController, DiscoverController, InspirationController, McpController, TranslationController, TravelController, FavoritesController, HistoryController, HotelsController, VisitorsController]
const providers = [PrismaService, QueueService, LlmService, OpenAiCompatibleProvider, McpClientService, McpRegistryService, XiaohongshuProvider, DouyinProvider, BilibiliProvider, WeiboProvider, KstayProvider, TavilyInspirationProvider, TasksService, DiscoverService, InspirationService, HotelsService, TranslationService, CoordinatorService, IntentAgent, ResearchAgent, PlannerAgent, CriticAgent, FavoritesService]
@Module({ imports: [ConfigModule.forRoot({ isGlobal: true })], controllers, providers })
export class AppModule implements NestModule { configure(consumer: MiddlewareConsumer) { consumer.apply(VisitorMiddleware).forRoutes('*') } }
