import { Bell, ChevronRight, Clock3, Globe2, Heart, History, Languages, Map, Settings, UserRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { EmptyState, PageIntro, PlaceCard } from '../../components/common'
import { useAppData } from '../../hooks/useAppData'
import { useState } from 'react'

export function ProfilePage() { const { favorites, history, plan }=useAppData(); return <div className="shell page profile"><section className="profile-head"><div className="avatar"><UserRound/></div><div><p className="eyebrow">MY KOREAMATE</p><h1>你好，旅行者</h1><span>下一站，也许是秋天的首尔。</span></div></section><div className="stats"><div><strong>{plan?1:0}</strong><span>我的行程</span></div><div><strong>{favorites.length}</strong><span>收藏地点</span></div><div><strong>{history.length}</strong><span>最近记录</span></div></div><div className="profile-grid"><section><h2>我的内容</h2><Link to="/travel/result"><span><Map/>我的旅行</span><ChevronRight/></Link><Link to="/profile/favorites"><span><Heart/>我的收藏</span><ChevronRight/></Link><Link to="/profile/history"><span><History/>历史记录</span><ChevronRight/></Link></section><section><h2>偏好与设置</h2><Link to="/settings"><span><Settings/>应用设置</span><ChevronRight/></Link><Link to="/translate"><span><Languages/>常用翻译</span><ChevronRight/></Link><Link to="/discover"><span><Globe2/>探索更多城市</span><ChevronRight/></Link></section></div></div> }
export function FavoritesPage() { const { favoritePlaces }=useAppData(); return <div className="shell page"><PageIntro eyebrow="SAVED PLACES" title="我的收藏" description="把想去的地方留在这里，下一次规划行程时更轻松。"/>{favoritePlaces.length?<div className="places-grid">{favoritePlaces.map((p)=><PlaceCard key={p.id} place={p}/>)}</div>:<EmptyState title="还没有收藏地点" description="在发现页点击心形按钮，就能把喜欢的地方保存到这里。" action="去发现" to="/discover"/>}</div> }
export function HistoryPage() { const { history }=useAppData(); return <div className="shell page"><PageIntro eyebrow="RECENT ACTIVITY" title="历史记录" description="最近的翻译与旅行规划，按时间集中整理。"/>{history.length?<div className="history-list">{history.map((item)=><article key={item.id}><span className={item.type}><Clock3/></span><div><small>{item.type==='translation'?'翻译记录':'旅行规划'} · {new Date(item.createdAt).toLocaleString('zh-CN')}</small><h3>{item.title}</h3><p>{item.detail}</p></div></article>)}</div>:<EmptyState title="暂时没有记录" description="完成一次翻译或生成行程后，记录会自动保存在这里。" action="试试翻译" to="/translate"/>}</div> }
export function SettingsPage() { const [notice,setNotice]=useState(true); const [language,setLanguage]=useState('zh-CN'); return <div className="shell page settings-page"><PageIntro eyebrow="PREFERENCES" title="设置" description="调整界面语言与演示偏好。设置只保留在当前页面。"/><section><label><span><Globe2/><span><strong>界面语言</strong><small>选择你习惯的显示语言</small></span></span><select value={language} onChange={(e)=>setLanguage(e.target.value)}><option value="zh-CN">简体中文</option><option value="ko">한국어（演示）</option><option value="en">English（演示）</option></select></label><label><span><Bell/><span><strong>行程提醒</strong><small>在演示中显示出发前提示</small></span></span><button role="switch" aria-checked={notice} className={`switch ${notice?'on':''}`} onClick={()=>setNotice(!notice)}><span/></button></label></section><p>当前为 KoreaMate V0.1 · 所有数据均为本地 Mock 演示。</p></div> }
