import { ArrowRight, CalendarDays, Check, Clock3, Coins, MapPin, Sparkles, Users } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { cities } from '../../data'
import { EmptyState, PageIntro, Visual } from '../../components/common'
import { useAppData } from '../../hooks/useAppData'
import { api } from '../../services/api'
import { storage } from '../../storage'
import type { TravelPreferences } from '../../types'

const interests = ['经典景点', '韩国美食', '咖啡探店', '韩剧取景', '购物', '自然徒步']
const defaults: TravelPreferences = { cityId: 'seoul', days: 3, people: 2, budget: 6000, interests: ['经典景点', '韩国美食'], note: '' }
export function TravelHome() { return <div className="shell page"><section className="travel-hero"><div><p className="eyebrow">AI TRIP DESIGNER</p><h1>不赶路，<br/>去过真正喜欢的旅行</h1><p>选一座城市，说说你的节奏与偏好。KoreaMate 会把每天的路线、花费与交通安排得刚刚好。</p><Link className="button" to="/travel/planner">开始定制行程 <ArrowRight size={18}/></Link></div><Visual tone="travel" label="韩国旅行地图与街景"/></section><section className="section steps"><p className="eyebrow">HOW IT WORKS</p><h2>三步，得到专属韩国行程</h2><div>{[['01','告诉我旅行偏好','城市、天数、人数与预算'],['02','生成每日路线','景点、美食与交通自然衔接'],['03','随时回来查看','收藏结果，旅途中也能快速找到']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section></div> }
export function TravelPlanner() {
  const saved = storage.getDraft(); const location = useLocation(); const question = (location.state as { question?: string } | null)?.question
  const [form, setForm] = useState<TravelPreferences>({ ...(saved ?? defaults), note: question || saved?.note || '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const { savePlan, addHistory } = useAppData(); const navigate = useNavigate()
  const set = <K extends keyof TravelPreferences>(key: K, value: TravelPreferences[K]) => { const next = { ...form, [key]: value }; setForm(next); storage.setDraft(next) }
  const toggle = (item: string) => set('interests', form.interests.includes(item) ? form.interests.filter((x) => x !== item) : [...form.interests, item])
  async function submit(e: FormEvent) { e.preventDefault(); if (form.days < 1 || form.days > 10 || form.people < 1 || form.budget < 500) { setError('请填写 1–10 天、至少 1 人且预算不少于 ¥500 的有效信息。'); return } setError(''); setLoading(true); try { const plan = await api.createPlan(form); savePlan(plan); addHistory({ id: crypto.randomUUID(), type: 'travel', title: plan.title, detail: `${form.people} 人 · ¥${form.budget}`, createdAt: new Date().toISOString() }); navigate('/travel/result') } catch { setError('行程生成失败，请稍后重试。') } finally { setLoading(false) } }
  return <div className="shell page planner"><PageIntro eyebrow="PLAN YOUR TRIP" title="先告诉我，你想怎样旅行" description="不用一次想清所有细节，填下最在意的部分就好。"/><form onSubmit={submit}><fieldset><legend><span>01</span>选择目的地</legend><div className="city-options">{cities.map((city)=><label key={city.id} className={form.cityId === city.id ? 'selected' : ''}><input type="radio" name="city" value={city.id} checked={form.cityId === city.id} onChange={() => set('cityId', city.id)}/><Visual tone={city.image} label={city.name}/><strong>{city.name}</strong><small>{city.koreanName}</small></label>)}</div></fieldset><fieldset><legend><span>02</span>旅行基本信息</legend><div className="form-grid"><label><CalendarDays/>旅行天数<input type="number" min="1" max="10" value={form.days} onChange={(e)=>set('days',Number(e.target.value))}/><small>建议 3–7 天</small></label><label><Users/>同行人数<input type="number" min="1" max="12" value={form.people} onChange={(e)=>set('people',Number(e.target.value))}/><small>包含你自己</small></label><label><Coins/>总预算（人民币）<input type="number" min="500" step="100" value={form.budget} onChange={(e)=>set('budget',Number(e.target.value))}/><small>不含往返机票</small></label></div></fieldset><fieldset><legend><span>03</span>你喜欢什么</legend><div className="chip-group">{interests.map((item)=><button type="button" className={form.interests.includes(item)?'selected':''} onClick={()=>toggle(item)} key={item}>{form.interests.includes(item)&&<Check size={15}/>} {item}</button>)}</div><label className="note-label">还有什么特别期待？<textarea value={form.note} onChange={(e)=>set('note',e.target.value)} placeholder="例如：节奏慢一点，想去韩剧取景地，不太能吃辣……"/></label></fieldset>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button generate" disabled={loading}><Sparkles/>{loading?'正在为你编排行程…':'生成我的韩国行程'}</button></form></div>
}
export function TravelResult() {
  const { plan } = useAppData(); const [active, setActive] = useState(0)
  if (!plan) return <div className="shell page"><EmptyState title="还没有生成过行程" description="先告诉我们目的地和旅行偏好，几秒钟就能得到一份完整计划。" action="开始规划" to="/travel/planner"/></div>
  const city = cities.find((c)=>c.id===plan.cityId)!; const day = plan.days[active]
  return <div className="shell page result-page"><header className="result-hero"><div><span className="pill">已为你生成</span><h1>{plan.title}</h1><p><MapPin/> {city.name} · <Users/> {plan.people} 人 · <CalendarDays/> {plan.days.length} 天</p></div><Link className="secondary" to="/travel/planner">重新规划</Link></header><div className="result-layout"><aside><p className="eyebrow">YOUR DAYS</p>{plan.days.map((item,i)=><button className={active===i?'active':''} onClick={()=>setActive(i)} key={item.day}><span>Day {item.day}</span><strong>{item.title}</strong></button>)}</aside><section className="itinerary"><div className="day-title"><div><p>DAY {day.day}</p><h2>{day.title}</h2><span>{day.summary}</span></div><Clock3/></div><div className="timeline">{day.activities.map((activity)=><article key={activity.time}><time>{activity.time}</time><div><h3>{activity.title}</h3><p>{activity.detail}</p><span>{activity.transport}</span></div><strong>¥{activity.cost}</strong></article>)}</div></section><aside className="budget-card"><p className="eyebrow">BUDGET</p><h2>预算概览</h2>{[['餐饮',plan.budget.food],['交通',plan.budget.transport],['门票',plan.budget.tickets],['购物与机动',plan.budget.shopping]].map(([label,value])=><div key={label}><span>{label}</span><strong>¥{value}</strong></div>)}<footer><span>总预算</span><strong>¥{plan.budget.total}</strong></footer></aside></div>{plan.references?.length?<section className="plan-references"><p className="eyebrow">TRAVEL REFERENCES</p><h2>本次行程参考</h2><div>{plan.references.map((reference)=><a href={reference.sourceUrl} target="_blank" rel="noreferrer" key={reference.sourceUrl}><strong>{reference.title}</strong><span>{reference.platform==='xiaohongshu'?'小红书':reference.platform==='web'?'网页攻略':reference.platform} · {reference.authorName}</span></a>)}</div></section>:null}</div>
}
