import { ArrowLeftRight, Check, Circle, FileVideo, Languages, Mic, Pause, Play, RotateCcw, Sparkles, Upload } from 'lucide-react'
import { useRef, useState, type ChangeEvent } from 'react'
import { languages } from '../../data'
import { useAppData } from '../../hooks/useAppData'
import { api } from '../../services/api'
import type { TranslationMode, TranslationResult, VideoTaskStep, VoiceState } from '../../types'
import { PageIntro } from '../../components/common'

function LanguageSelector({ source, target, onSource, onTarget }: { source: string; target: string; onSource: (v: string) => void; onTarget: (v: string) => void }) {
  const swap = () => { onSource(target); onTarget(source) }
  return <div className="language-row"><label>输入语言<select value={source} onChange={(e) => onSource(e.target.value)}>{languages.map((l) => <option value={l.code} key={l.code}>{l.label} · {l.nativeLabel}</option>)}</select></label><button className="icon-button" onClick={swap} aria-label="交换语言"><ArrowLeftRight size={19}/></button><label>翻译为<select value={target} onChange={(e) => onTarget(e.target.value)}>{languages.map((l) => <option value={l.code} key={l.code}>{l.label} · {l.nativeLabel}</option>)}</select></label></div>
}
function TextPanel({ source, target }: { source: string; target: string }) {
  const [text, setText] = useState('我想去景福宫。'); const [result, setResult] = useState<TranslationResult | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const { addHistory } = useAppData()
  async function translate() { if (!text.trim()) { setError('请输入需要翻译的内容'); return } setError(''); setLoading(true); try { const next = await api.translate(text, source, target); setResult(next); addHistory({ id: crypto.randomUUID(), type: 'translation', title: text, detail: next.translated, createdAt: new Date().toISOString() }) } catch { setError('翻译暂时失败，请重试。') } finally { setLoading(false) } }
  return <div className="translate-panel"><div className="text-workspace"><div><label htmlFor="source-text">输入内容</label><textarea id="source-text" value={text} maxLength={500} onChange={(e) => setText(e.target.value)} /><span className="counter">{text.length}/500</span>{error && <p className="field-error" role="alert">{error}</p>}<button className="button" disabled={loading} onClick={translate}><Sparkles size={18}/>{loading ? '正在翻译…' : '开始翻译'}</button></div><div className="result-box" aria-live="polite"><span>翻译结果</span>{result ? <><h2 lang="ko">{result.translated}</h2><p>{result.romanization}</p></> : <div className="result-placeholder"><Languages/><p>翻译结果会显示在这里</p></div>}</div></div>{result && <div className="explain-grid"><section><h3>词语解释</h3>{result.words.map((w) => <div className="word" key={w.korean}><strong lang="ko">{w.korean}</strong><span>{w.chinese}</span></div>)}</section><section><h3>使用场景</h3><p>{result.context}</p><span className="tip">旅行沟通 · 礼貌表达</span></section></div>}</div>
}
function VoicePanel() {
  const [state, setState] = useState<VoiceState>('idle'); const timer = useRef<number | undefined>(undefined)
  const start = () => { setState('listening'); timer.current = window.setTimeout(() => setState('result'), 1600) }
  const reset = () => { if (timer.current) clearTimeout(timer.current); setState('idle') }
  return <div className="voice-panel" aria-live="polite"><div className={`mic-orbit ${state === 'listening' ? 'listening' : ''}`}><button aria-label={state === 'listening' ? '停止录音' : '开始录音'} onClick={state === 'idle' ? start : state === 'listening' ? () => setState('result') : reset}>{state === 'listening' ? <Pause/> : state === 'result' ? <RotateCcw/> : <Mic/>}</button></div><h2>{state === 'idle' ? '点击麦克风开始讲话' : state === 'listening' ? '正在聆听…' : '识别完成'}</h2><p>{state === 'idle' ? '本版本将模拟一段韩语语音识别' : state === 'listening' ? '00:03 · 再次点击即可停止' : '已为你整理识别原文与中文翻译'}</p>{state === 'result' && <div className="voice-result"><div><span>识别原文</span><h3 lang="ko">안녕하세요. 경복궁은 어디예요?</h3></div><div><span>中文翻译</span><h3>你好，请问景福宫在哪里？</h3></div><button className="secondary"><Play size={17}/> 播放韩语（模拟）</button></div>}</div>
}
const initialSteps: VideoTaskStep[] = ['视频解析', '音频提取', '韩语语音识别', '中文字幕翻译', '字幕生成'].map((label, i) => ({ id: `${i}`, label, status: 'pending' }))
function VideoPanel() {
  const [file, setFile] = useState<File | null>(null); const [steps, setSteps] = useState(initialSteps); const [running, setRunning] = useState(false); const [error, setError] = useState('')
  function choose(e: ChangeEvent<HTMLInputElement>) { const next = e.target.files?.[0] ?? null; if (next && !['video/mp4', 'video/quicktime', 'video/x-matroska'].includes(next.type) && !next.name.match(/\.(mp4|mov|mkv)$/i)) { setError('请选择 MP4、MOV 或 MKV 视频'); setFile(null); return } setError(''); setFile(next); setSteps(initialSteps) }
  async function run() { if (!file) { setError('请先选择一个视频文件'); return } setRunning(true); for (let i = 0; i < initialSteps.length; i++) { setSteps((all) => all.map((s, idx) => ({ ...s, status: idx < i ? 'done' : idx === i ? 'active' : 'pending' }))); await new Promise((r) => setTimeout(r, 380)) } setSteps((all) => all.map((s) => ({ ...s, status: 'done' }))); setRunning(false) }
  return <div className="video-panel"><label className="upload-box"><input type="file" accept=".mp4,.mov,.mkv,video/mp4,video/quicktime" onChange={choose}/><span className="upload-icon"><Upload/></span><strong>{file ? file.name : '选择一段韩国视频'}</strong><span>{file ? `${(file.size / 1024 / 1024).toFixed(1)} MB · 仅用于本地模拟` : 'MP4 / MOV / MKV · 文件不会上传'}</span></label>{error && <p className="field-error" role="alert">{error}</p>}<button className="button" onClick={run} disabled={running}><FileVideo size={18}/>{running ? '正在生成字幕…' : '开始视频翻译'}</button>{steps.some((s) => s.status !== 'pending') && <div className="progress-card" aria-live="polite"><h3>处理进度</h3>{steps.map((step) => <div className={step.status} key={step.id}>{step.status === 'done' ? <Check/> : step.status === 'active' ? <span className="spinner"/> : <Circle/>}<span>{step.label}</span><small>{step.status === 'done' ? '已完成' : step.status === 'active' ? '处理中' : '等待中'}</small></div>)}</div>}</div>
}
export default function TranslationPage() {
  const [mode, setMode] = useState<TranslationMode>('text'); const [source, setSource] = useState('zh-CN'); const [target, setTarget] = useState('ko-KR')
  return <div className="shell page"><PageIntro eyebrow="TRANSLATION STUDIO" title="懂韩语，也懂你的场景" description="文字、语音与视频都在同一个工作台，切换输入方式即可继续。"/><div className="workspace"><LanguageSelector source={source} target={target} onSource={setSource} onTarget={setTarget}/><div className="mode-tabs" role="tablist" aria-label="翻译方式">{([{ id: 'text', label: '文字', icon: Languages }, { id: 'voice', label: '语音', icon: Mic }, { id: 'video', label: '视频', icon: FileVideo }] as const).map(({ id, label, icon: Icon }) => <button key={id} role="tab" aria-selected={mode === id} onClick={() => setMode(id)}><Icon size={18}/>{label}</button>)}</div><div role="tabpanel">{mode === 'text' ? <TextPanel source={source} target={target}/> : mode === 'voice' ? <VoicePanel/> : <VideoPanel/>}</div></div></div>
}
