import { ArrowRight, Compass, Languages, MapPinned, Sparkles } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { cities, places } from '../data'
import { PlaceCard, Visual } from '../components/common'

export default function HomePage() {
  const [question, setQuestion] = useState(''); const navigate = useNavigate()
  function submit(e: FormEvent) { e.preventDefault(); navigate('/travel/planner', { state: { question } }) }
  return <div className="home"><section className="hero shell"><div className="hero-copy"><p className="eyebrow">YOUR KOREA COMPANION</p><h1>探索韩国，<br/><em>从语言到旅行</em></h1><p>翻译韩语、规划行程、发现值得专程前往的地方。把陌生旅程，变成自在日常。</p><form className="ask" onSubmit={submit}><Sparkles size={20}/><label className="sr-only" htmlFor="hero-question">描述旅行需求</label><input id="hero-question" value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="问我：帮我规划首尔 5 天行程……"/><button aria-label="开始规划"><ArrowRight/></button></form><div className="hero-notes"><span>中韩翻译</span><span>个性行程</span><span>城市灵感</span></div></div><div className="hero-art"><Visual tone="hero" label="首尔城市与宫殿风景"/><div className="floating-note"><span>오늘의 서울</span><strong>24° 晴朗，适合散步</strong></div></div></section><section className="shell section"><div className="section-head"><div><p className="eyebrow">START HERE</p><h2>今天想从哪里开始？</h2></div></div><div className="feature-grid"><Link className="feature-card coral" to="/translate"><Languages/><div><h3>AI 翻译</h3><p>文字、语音、视频，一站式理解韩语</p></div><ArrowRight className="arrow"/></Link><Link className="feature-card sage" to="/travel/planner"><MapPinned/><div><h3>AI 旅行规划</h3><p>告诉我偏好，生成专属韩国行程</p></div><ArrowRight className="arrow"/></Link></div></section><section className="shell section"><div className="section-head"><div><p className="eyebrow">CHOOSE A CITY</p><h2>先选一座喜欢的城市</h2></div><Link to="/discover">查看全部 <ArrowRight size={17}/></Link></div><div className="city-grid">{cities.map((city) => <Link className="city-card" key={city.id} to={`/discover/${city.id}`}><Visual tone={city.image} label={`${city.name}旅行风景`}/><div><p>{city.koreanName}</p><h3>{city.name} <small>{city.englishName}</small></h3><span>{city.tagline}</span></div></Link>)}</div></section><section className="shell section"><div className="section-head"><div><p className="eyebrow">CURATED FOR YOU</p><h2>韩国灵感精选</h2></div><Link to="/discover"><Compass size={17}/> 去发现</Link></div><div className="places-grid">{places.slice(0, 3).map((p) => <PlaceCard key={p.id} place={p}/>)}</div></section></div>
}
